### ISSUE TITLE
Full disk encryption

### ISSUE THREAD

**Issue by lhaecker** [swayos/swayos.github.io#11]
Hi dear Developer,

I would like to ask if full disk encryption would be feasible in SwayOS? I will send you an example:
https://gist.github.com/huntrar/e42aee630bee3295b2c671d098c81268

If possible, could you make it happen?

Regards,
Laszlo

**Comment by milgra** [comment]
Hi, I would like to make it happen but the current way of installing swayos - dd-ing a pre-installed image to the target disk - makes it complicated, I will experiment with it.

**Comment by swayos** [comment]
Hi, I dropped the pre-built installer, I recommend void linux for a 2-minute install experience, the use the setup script, it supports void now.
