### ISSUE TITLE
Download link doest work as expected

### ISSUE THREAD

**Issue by farseenmanekhan1232** [swayos/swayos.github.io#3]
I have tried downloading iso file multiple times , and every time the file downloads till 1024 mb and then shows error
I have tried it on chrome , firefox and also tried downloading using Internet Download Manager

**Comment by tiagaoalb** [comment]
> I have tried downloading iso file multiple times , and every time the file downloads till 1024 mb and then shows error I have tried it on chrome , firefox and also tried downloading using Internet Download Manager

Same here.

**Comment by milgra** [comment]
I added the ISO to my google drive, is it faster? 
[https://drive.google.com/drive/folders/1QN9WZD2Ij2WE7QJ7IpHQDpHaP7rSk4Fs](https://drive.google.com/drive/folders/1QN9WZD2Ij2WE7QJ7IpHQDpHaP7rSk4Fs)

I will also setup a torrent link for the ISO's

**Comment by tiagaoalb** [comment]
> I added the ISO to my google drive, is it faster? https://drive.google.com/drive/folders/1QN9WZD2Ij2WE7QJ7IpHQDpHaP7rSk4Fs
> 
> I will also setup a torrent link for the ISO's

Thank you very much 👊🏻

**Comment by swayos** [comment]
Torrent is finally ready, it will always be under release files : 
https://github.com/swayos/swayos.github.io/releases/download/20220512/swayos-2022.05.12-x86_64.iso.torrent
