### ISSUE TITLE
What is the status of this this project?

### ISSUE THREAD

**Issue by vil** [swayos/swayos.github.io#36]
Hi,

Is this project maintained anymore? As the installer doesn't work properly anymore.

- `libvpx6-devel` doesn't exist anymore, as it seems to be replaced with `libvpx-devel`
- `vmp` fails to build.
- `ffmpeg` is few versions behind.
- `mmfm` seems to fail building too.
- ....

I tested installing this on a VM, but it also failed on actual hardware too.

..I'll continue troubleshooting this to see if theres any other problems.

^^^
This is on Void Linux

**Comment by swayos** [comment]
Hi, version 3.0 is ready now, I removed the installer scripts and provided a step by step installation.
